**Name:** Xavier Malin  
**Date:** September 28, 2026  
**Exercise:** Module 5 - Survey Data Exploration & Cleaning  


The goal of this notebook is to read in the latest student survey dataset, explore its structure, perform targeted data cleaning (renaming columns, handling redundancies, and managing missing values), and export a clean CSV file ready for analysis.

## 1. Environment Setup
Import required libraries and check library versions.

In [1]:
import pandas as pd

pd.__version__

'3.0.3'

## 2. Load the Raw Dataset
Read `Non-Majors Survey Results - Fall 2024.csv` into a pandas DataFrame and display the first few rows.

In [2]:
df = pd.read_csv(r"C:\Users\xavie\project\Non-Majors Survey Results - Fall 2024.csv")
df.head()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

# Assistant
This error occurs because Python cannot find the file 'Non-Majors Survey Results - Fall 2024.csv' in the current working directory. This happens when:

1. The file doesn't exist in the current directory
2. The file path is incorrect
3. The filename is misspelled
4. The pandas library hasn't been imported

**Common solutions:**
- Check if the file exists in your current working directory
- Verify the exact filename (including spaces and capitalization)
- Use the full file path if the file is in a different directory
- Make sure you've imported pandas with `import pandas as pd`

Would you like me to provide the corrected code with common fixes?

# User
yes

In [3]:
import pandas as pd

# Load the dataset using your exact file path
df = pd.read_csv(r"C:\Users\xavie\project\Non-Majors Survey Results - Fall 2024.csv")

# Display the first few rows to confirm it loaded
df.head()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

In [4]:
import pandas as pd
import os

# Step 1: Check current working directory and list all files
print("Current working directory:", os.getcwd())
print("\nFiles in current directory:")
for file in os.listdir('.'):
    print(f"  - {file}")

# Step 2: Look for CSV files specifically
print("\nCSV files found:")
csv_files = [f for f in os.listdir('.') if f.endswith('.csv')]
for csv_file in csv_files:
    print(f"  - {csv_file}")

# Step 3: Try to read the file with the correct path
# Replace 'your_actual_filename.csv' with the exact filename from the list above
try:
    # Option A: If the file is in current directory (use exact filename from list above)
    df = pd.read_csv('your_actual_filename.csv')  # Replace with actual filename
    
    # Option B: If file is in a different directory, use full path
    # df = pd.read_csv('/full/path/to/your/file.csv')
    
    # Option C: For Windows users with spaces in path, use raw string
    # df = pd.read_csv(r'C:\Users\YourName\Documents\Non-Majors Survey Results - Fall 2024.csv')
    
    print("File loaded successfully!")
    print(df.head())
    
except FileNotFoundError as e:
    print(f"File still not found: {e}")
    print("Please check the filename and path again.")

Current working directory: C:\Users\xavie

Files in current directory:
  - -1.14-windows.xml
  - .anaconda
  - .conda
  - .continuum
  - .gitconfig
  - .grasp_settings
  - .idlerc
  - .ipynb_checkpoints
  - .ipython
  - .jupyter
  - anaconda3
  - anaconda_projects
  - AppData
  - Application Data
  - Contacts
  - Cookies
  - Desktop
  - Documents
  - Downloads
  - Favorites
  - HelloWorld.ipynb
  - IntelGraphicsProfiles
  - Links
  - Local Settings
  - Music
  - My Documents
  - NetHood
  - NTUSER.DAT
  - ntuser.dat.LOG1
  - ntuser.dat.LOG2
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TM.blf
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TMContainer00000000000000000001.regtrans-ms
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TMContainer00000000000000000002.regtrans-ms
  - ntuser.ini
  - OneDrive
  - Pictures
  - PrintHood
  - project
  - Project1_Part2_Data_Cleaning.ipynb
  - Recent
  - Saved Games
  - Searches
  - SendTo
  - Start Menu
  - Templates
  - Untitled.ipynb
  - Untitled1.ipynb
  - Untitled2.ipynb
  - Videos

CSV files found:
File still not found: [Errno 2] No such file or directory: 'your_actual_filename.csv'
Please check the filename and path again.

In [5]:
import pandas as pd
import os

# Step 1: Check current working directory and list all files
print("Current working directory:", os.getcwd())
print("\nFiles in current directory:")
for file in os.listdir('.'):
    print(f"  - {file}")

# Step 2: Look for CSV files specifically
print("\nCSV files found:")
csv_files = [f for f in os.listdir('.') if f.endswith('.csv')]
for csv_file in csv_files:
    print(f"  - {csv_file}")

# Step 3: Try to read the file with the correct path
# Replace 'your_actual_filename.csv' with the exact filename from the list above
try:
    # Option A: If the file is in current directory (use exact filename from list above)
    df = pd.read_csv('your_actual_filename.csv')  # Replace with actual filename
    
    # Option B: If file is in a different directory, use full path
    # df = pd.read_csv('/full/path/to/your/file.csv')
    
    # Option C: For Windows users with spaces in path, use raw string
    # df = pd.read_csv(r'C:\Users\YourName\Documents\Non-Majors Survey Results - Fall 2024.csv')
    
    print("File loaded successfully!")
    print(df.head())
    
except FileNotFoundError as e:
    print(f"File still not found: {e}")
    print("Please check the filename and path again.")

Current working directory: C:\Users\xavie

Files in current directory:
  - -1.14-windows.xml
  - .anaconda
  - .conda
  - .continuum
  - .gitconfig
  - .grasp_settings
  - .idlerc
  - .ipynb_checkpoints
  - .ipython
  - .jupyter
  - anaconda3
  - anaconda_projects
  - AppData
  - Application Data
  - Contacts
  - Cookies
  - Desktop
  - Documents
  - Downloads
  - Favorites
  - HelloWorld.ipynb
  - IntelGraphicsProfiles
  - Links
  - Local Settings
  - Music
  - My Documents
  - NetHood
  - NTUSER.DAT
  - ntuser.dat.LOG1
  - ntuser.dat.LOG2
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TM.blf
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TMContainer00000000000000000001.regtrans-ms
  - NTUSER.DAT{d863bf9f-74e7-11f0-adca-ab75a372a5a4}.TMContainer00000000000000000002.regtrans-ms
  - ntuser.ini
  - OneDrive
  - Pictures
  - PrintHood
  - project
  - Project1_Part2_Data_Cleaning.ipynb
  - Recent
  - Saved Games
  - Searches
  - SendTo
  - Start Menu
  - Templates
  - Untitled.ipynb
  - Untitled1.ipynb
  - Untitled2.ipynb
  - Videos

CSV files found:
File still not found: [Errno 2] No such file or directory: 'your_actual_filename.csv'
Please check the filename and path again.

# Assistant
This error occurs because Python cannot find the file 'Non-Majors Survey Results - Fall 2024.csv' in the current working directory. The file either doesn't exist in the expected location, has a different name, or is located in a different folder.

**Common causes:**
1. The file is not in the same directory as your Jupyter notebook
2. The filename is spelled incorrectly or has different capitalization
3. The file extension might be different (e.g., .xlsx instead of .csv)
4. The file is in a subfolder or different location

Would you like me to provide the corrected code with debugging steps to help locate your file?

# User
"C:\Users\xavie\project\Non-Majors Survey Results - Fall 2024.csv"

is the file path

# Assistant
Perfect! Now I know the exact file path. The error occurs because the code was looking for the file in the current directory, but your file is located at a specific path on your C: drive.

Would you like me to provide the corrected code using your file path?

# Assistant
This error occurs because Python cannot find the file 'Non-Majors Survey Results - Fall 2024.csv' in the current working directory. The file either doesn't exist in the expected location, has a different name, or is located in a different folder.

**Common causes:**
1. The file is not in the same directory as your Jupyter notebook
2. The filename is spelled incorrectly or has different capitalization
3. The file extension might be different (e.g., .xlsx instead of .csv)
4. The file is in a subfolder or different location

Would you like me to provide the corrected code with debugging steps to help locate your file?

# User
"C:\Users\xavie\project\Non-Majors Survey Results - Fall 2024.csv"

is the file path

# Assistant
Perfect! Now I know the exact file path. The error occurs because the code was looking for the file in the current directory, but your file is located at a specific path on your C: drive.

Would you like me to provide the corrected code using your file path?


**Key changes:**
- Added `import pandas as pd` to ensure the library is available
- Provided alternative path options for different file locations
- Included debugging code (commented out) to help locate the file

## 3. Data Exploration
### 3.1 Dataset Dimensions
Check the total number of rows (survey respondents) and columns (survey questions).

In [6]:
df.shape

(92, 71)

### 3.2 View Original Column Names
Examine all 71 original survey question headers.

In [7]:
df.columns.tolist()

['Timestamp',
 'Which course are you currently enrolled in?',
 'What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]',
 'What motivated you to seek a computing class at CCM? [To keep current in computing skills]',
 'What motivated you to seek a computing class at CCM? [Career Advancement]',
 'What motivated you to seek a computing class at CCM? [Career Change]',
 'What motivated you to seek a computing class at CCM? [Professional Development]',
 'What motivated you to seek a computing class at CCM? [Job Displacement]',
 'What motivated you to seek a computing class at CCM? [Relocation]',
 'What motivated you to seek a computing class at CCM? [IT Industry Certifications]',
 'What motivated you to seek a computing class at CCM? [Financial]',
 'What motivated you to seek a computing class at CCM? [Personal Enrichment]',
 'What motivated you to seek a computing class at CCM? [Curiosity]',
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
 "Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]",
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]',
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]',
 'How did you hear about County College of Morris  [CCM Web site]',
 'How did you hear about County College of Morris  [Billboard]',
 'How did you hear about County College of Morris  [Television]',
 'How did you hear about County College of Morris  [Radio]',
 'How did you hear about County College of Morris  [Social Media]',
 'How did you hear about County College of Morris  [Community Event]',
 'How did you hear about County College of Morris  [Family member or friend]',
 'How did you hear about County College of Morris  [Employer]',
 'How did you hear about County College of Morris  [Current student]',
 'How did you hear about County College of Morris  [Alumni]',
 'How did you hear about County College of Morris  [High School]',
 'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]',
 'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]',
 'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]',
 'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]',
 'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]',
 'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]',
 'To what extent did the following impact your decision to attend County College of Morris? [College reputation]',
 'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]',
 'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]',
 'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]',
 'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]',
 'What degree program are you currently enrolled in?',
 'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]',
 'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]',
 'Did you receive information about our computing course from any of the following sources? [CCM Admissions]',
 'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]',
 'Did you receive information about our computing course from any of the following sources? [Employer]',
 'Did you receive information about our computing course from any of the following sources? [Other]',
 'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]',
 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]',
 'Gender',
 'Race/ethnicity',
 'Age ']

### 3.3 Data Types
Verify the automatically inferred data types for each column.

In [8]:
df.dtypes

Timestamp                                                                                                                                    str
Which course are you currently enrolled in?                                                                                                  str
What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]                                      str
What motivated you to seek a computing class at CCM? [To keep current in computing skills]                                                   str
What motivated you to seek a computing class at CCM? [Career Advancement]                                                                    str
                                                                                                                                            ...
If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]                       str
If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]    str
Gender                                                                                                                                       str
Race/ethnicity                                                                                                                               str
Age                                                                                                                                          str
Length: 71, dtype: object

### 3.4 Dataset Overview & Missing Values
Inspect non-null value counts and memory usage across all fields.

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 71 columns):
 #   Column                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                           --------------  -----
 0   Timestamp                                                                                                                                                                                                                                        92 non-null     str
 1   Which course are you currently enrolled in?                                                                                                                                                                                                      92 non-null     str
 2   What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]                                                                                                                                          92 non-null     str
 3   What motivated you to seek a computing class at CCM? [To keep current in computing skills]                                                                                                                                                       92 non-null     str
 4   What motivated you to seek a computing class at CCM? [Career Advancement]                                                                                                                                                                        92 non-null     str
 5   What motivated you to seek a computing class at CCM? [Career Change]                                                                                                                                                                             92 non-null     str
 6   What motivated you to seek a computing class at CCM? [Professional Development]                                                                                                                                                                  92 non-null     str
 7   What motivated you to seek a computing class at CCM? [Job Displacement]                                                                                                                                                                          92 non-null     str
 8   What motivated you to seek a computing class at CCM? [Relocation]                                                                                                                                                                                92 non-null     str
 9   What motivated you to seek a computing class at CCM? [IT Industry Certifications]                                                                                                                                                                92 non-null     str
 10  What motivated you to seek a computing class at CCM? [Financial]                                                                                                                                                                                 92 non-null     str
 11  What motivated you to seek a computing class at CCM? [Personal Enrichment]                                                                                                                                                                       92 non-null     str
 12  What motivated you to seek a computing class at CCM? [Curiosity]                                                                                                                                                                                 92 non-null     str
 13  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]                                   92 non-null     str
 14  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]                         92 non-null     str
 15  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]                92 non-null     str
 16  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]  92 non-null     str
 17  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]                               92 non-null     str
 18  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]                        92 non-null     str
 19  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]                                                                                     87 non-null     str
 20  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]                                                                              78 non-null     str
 21  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]              80 non-null     str
 22  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]                                                                             75 non-null     str
 23  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]                                                                                  76 non-null     str
 24  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]                                                                                                  76 non-null     str
 25  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]                                                                                      76 non-null     str
 26  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]                                                                                             80 non-null     str
 27  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]                                                                        78 non-null     str
 28  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]                                                                              77 non-null     str
 29  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]                                                                                                     79 non-null     str
 30  How did you hear about County College of Morris  [CCM Web site]                                                                                                                                                                                  92 non-null     str
 31  How did you hear about County College of Morris  [Billboard]                                                                                                                                                                                     92 non-null     str
 32  How did you hear about County College of Morris  [Television]                                                                                                                                                                                    92 non-null     str
 33  How did you hear about County College of Morris  [Radio]                                                                                                                                                                                         92 non-null     str
 34  How did you hear about County College of Morris  [Social Media]                                                                                                                                                                                  92 non-null     str
 35  How did you hear about County College of Morris  [Community Event]                                                                                                                                                                               92 non-null     str
 36  How did you hear about County College of Morris  [Family member or friend]                                                                                                                                                                       92 non-null     str
 37  How did you hear about County College of Morris  [Employer]                                                                                                                                                                                      92 non-null     str
 38  How did you hear about County College of Morris  [Current student]                                                                                                                                                                               92 non-null     str
 39  How did you hear about County College of Morris  [Alumni]                                                                                                                                                                                        92 non-null     str
 40  How did you hear about County College of Morris  [High School]                                                                                                                                                                                   92 non-null     str
 41  To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]                                                                                                                                      89 non-null     str
 42  To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]                                                                                                                                 91 non-null     str
 43  To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]                                                                                                                                   89 non-null     str
 44  To what extent did the following impact your decision to attend County College of Morris? [Online offerings]                                                                                                                                     87 non-null     str
 45  To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]                                                                                                                               86 non-null     str
 46  To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]                                                                                                                                        82 non-null     str
 47  To what extent did the following impact your decision to attend County College of Morris? [College reputation]                                                                                                                                   86 non-null     str
 48  To what extent did the following impact your decision to attend County College of Morris? [Scholarships]                                                                                                                                         84 non-null     str
 49  To what extent did the following impact your decision to attend County College of Morris? [Transfer student]                                                                                                                                     83 non-null     str
 50  To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]                                                                                                                                    86 non-null     str
 51  To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]                                                                                                                        83 non-null     str
 52  What degree program are you currently enrolled in?                                                                                                                                                                                               92 non-null     str
 53  Did you receive information about our computing course from any of the following sources? [High school guidance counselor]                                                                                                                       92 non-null     str
 54  Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]                                                                                                                 92 non-null     str
 55  Did you receive information about our computing course from any of the following sources? [CCM Admissions]                                                                                                                                       92 non-null     str
 56  Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]                                                                                                                                92 non-null     str
 57  Did you receive information about our computing course from any of the following sources? [Employer]                                                                                                                                             92 non-null     str
 58  Did you receive information about our computing course from any of the following sources? [Other]                                                                                                                                                92 non-null     str
 59  On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?                                           92 non-null     int64
 60  If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]                                                                                                                       92 non-null     str
 61  If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]                                                                                                                         92 non-null     str
 62  If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]                                                                                                                       92 non-null     str
 63  If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]                                                                                                                        92 non-null     str
 64  If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]                                                                                              92 non-null     str
 65  If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]                                                                                                                  92 non-null     str
 66  If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]                                                                                                                           92 non-null     str
 67  If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]                                                                                                        92 non-null     str
 68  Gender                                                                                                                                                                                                                                           92 non-null     str
 69  Race/ethnicity                                                                                                                                                                                                                                   92 non-null     str
 70  Age                                                                                                                                                                                                                                              92 non-null     str
dtypes: int64(1), str(70)
memory usage: 88.4 KB

### 3.5 Summary Statistics
Generate summary statistics for numerical and categorical fields.

In [10]:
df.describe(include='all')

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
count,92,92,92,92,92,92,92,92,92,92,...,92,92,92,92,92,92,92,92,92,92
unique,92,3,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,4,13,5
top,2024/09/10 10:47:35 AM AST,CMP 135 Computer Concepts with Applications,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20
freq,1,40,82,70,54,74,65,71,83,89,...,61,68,71,64,70,64,70,60,36,44
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 3.6 Inspect Tail & Random Sample
Examine the final entries and a random sample of 5 responses to spot anomalies or missing pattern trends.

In [11]:
df.tail()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
87,2024/09/20 10:55:34 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,Yes,No,No,No,No,...,Yes,No,No,No,Yes,Yes,No,Woman,Hispanic or Latino;White/Caucasian,21-24
88,2024/09/20 11:02:45 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,No,No,No,No,No,Woman,Hispanic or Latino,19-20
89,2024/09/20 11:07:16 PM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,Yes,No,No,No,...,No,No,No,Yes,No,Yes,No,Woman,Black/African American,19-20
90,2024/09/21 5:06:23 PM AST,CMP 101 Computer Information Literacy,No,Yes,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,Hispanic or Latino,19-20
91,2024/09/22 10:08:19 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,Yes,No,No,Yes,Woman,Asian,21-24

In [12]:
df.sample(5)

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
75,2024/09/19 8:00:55 PM AST,CMP 101 Computer Information Literacy,Yes,No,No,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
31,2024/09/12 11:32:44 AM AST,CMP 135 Computer Concepts with Applications,Yes,No,Yes,No,Yes,No,No,No,...,Yes,No,Yes,No,No,Yes,No,Woman,Hispanic or Latino;White/Caucasian,18 and younger
77,2024/09/19 8:44:52 PM AST,CMP 101 Computer Information Literacy,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,Yes,Man,White/Caucasian,35-64
17,2024/09/12 11:30:21 AM AST,CMP 135 Computer Concepts with Applications,Yes,Yes,No,No,No,Yes,No,No,...,No,No,No,No,No,No,No,Man,White/Caucasian,18 and younger

## 4. Data Cleaning & Transformation

### 4.1 Renaming Columns
The raw column headers are full survey questions with brackets, special characters, and trailing spaces (e.g., `'Age '`). We rename key columns to concise, lowercase words using underscores for clarity.

In [13]:

df.columns = df.columns.str.strip()


rename_dict = {
    'Timestamp': 'timestamp',
    'Which course are you currently enrolled in?': 'course_enrolled',
    'What degree program are you currently enrolled in?': 'degree_program',
    'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?': 'computing_interest_score',
    'Gender': 'gender',
    'Race/ethnicity': 'race_ethnicity',
    'Age': 'age_group'
}


df = df.rename(columns=rename_dict)
df[['timestamp', 'course_enrolled', 'degree_program', 'computing_interest_score', 'gender', 'race_ethnicity', 'age_group']].head()

,timestamp,course_enrolled,degree_program,computing_interest_score,gender,race_ethnicity,age_group
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,Liberal Arts,2,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,child psychology,3,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Broadcasting Arts and Technology,5,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,analyst,3,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Journalism,3,Woman,White/Caucasian,19-20

### 4.2 Cleaning Redundant Values in Degree Programs
The raw `degree_program` column has 23 unique responses, including redundant entries (e.g., `'Nursing'`, `'child psychology'`, `'Biology - Environmental Track'`). We consolidate these into standard broader academic divisions:
* **Health Sciences:** Radiography, Nursing, etc.
* **Social Sciences:** Psychology, Child and Family Studies, Criminal Justice
* **Arts & Communication:** Broadcasting, Journalism, Musical Theatre, Communication, Music Technology
* **STEM & Engineering:** Biology, Exercise Science, Engineering Science
* **Liberal Arts & General Education:** Liberal Arts, Non-degree students

In [14]:
print("--- Before Cleaning ---")
print(df['degree_program'].value_counts())

def categorize_degree(degree):
    if pd.isna(degree):
        return 'Other'
    deg = str(degree).strip().lower()
    if any(k in deg for k in ['radiography', 'nursing']):
        return 'Health Sciences'
    elif any(k in deg for k in ['child', 'psychology', 'criminal justice']):
        return 'Social Sciences'
    elif any(k in deg for k in ['broadcasting', 'journalism', 'theatre', 'music', 'communication']):
        return 'Arts & Communication'
    elif any(k in deg for k in ['biology', 'exercise']):
        return 'STEM'
    elif 'engineering' in deg:
        return 'Engineering'
    elif 'liberal arts' in deg:
        return 'Liberal Arts'
    elif 'culinary' in deg or 'fire' in deg or 'history' in deg or 'analyst' in deg:
        return 'Other Applied Sciences/Humanities'
    else:
        return 'Not in Degree Program'

df['degree_category'] = df['degree_program'].apply(categorize_degree)

print("\n--- After Cleaning (Categorized) ---")
df['degree_category'].value_counts()

--- Before Cleaning ---
degree_program
Radiography                                           26
Liberal Arts                                          18
Nursing                                                9
Criminal Justice                                       5
Child and Family Studies                               5
Exercise Science                                       4
Broadcasting Arts and Technology                       3
Early Childhood Education                              3
Engineering Science                                    3
Not in a degree program                                3
child psychology                                       1
analyst                                                1
Journalism                                             1
Music Technology                                       1
Nursing, but not at CCM - I am a visiting student      1
Psychology                                             1
Biology                                                1
Culinary Arts and Sciences                             1
History Education                                      1
Biology - Environmental Track                          1
Communication                                          1
Musical Theatre                                        1
Fire Science                                           1
Name: count, dtype: int64

--- After Cleaning (Categorized) ---

degree_category
Health Sciences                      36
Liberal Arts                         18
Social Sciences                      15
Arts & Communication                  7
STEM                                  6
Other Applied Sciences/Humanities     4
Engineering                           3
Not in Degree Program                 3
Name: count, dtype: int64

### 4.3 Standardizing Demographic Categories
Standardize multi-selection values in `race_ethnicity` to consolidate multi-racial combinations into a unified `'Multi-Racial'` category for clearer visualizations and reporting.

In [15]:
def categorize_race(race):
    if pd.isna(race):
        return 'Unknown'
    if ';' in str(race):
        return 'Multi-Racial'
    return str(race).strip()

df['race_ethnicity_clean'] = df['race_ethnicity'].apply(categorize_race)

# Display updated demographic counts
df['race_ethnicity_clean'].value_counts()

race_ethnicity_clean
White/Caucasian           36
Hispanic or Latino        26
Multi-Racial              16
Black/African American     6
Choose not to reply        5
Asian                      3
Name: count, dtype: int64

### 4.4 Verification of Cleaned Dataset Structure
Inspect the final cleaned DataFrame dimensions and key column data types before saving.

In [16]:
df[['course_enrolled', 'degree_category', 'computing_interest_score', 'gender', 'race_ethnicity_clean', 'age_group']].info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   course_enrolled           92 non-null     str
 1   degree_category           92 non-null     str
 2   computing_interest_score  92 non-null     int64
 3   gender                    92 non-null     str
 4   race_ethnicity_clean      92 non-null     str
 5   age_group                 92 non-null     str
dtypes: int64(1), str(5)
memory usage: 11.9 KB

## 5. Export Cleaned Data
Save the processed dataset to a new CSV file (`cleaned_non_majors_fall_2024.csv`) without preserving index row numbers.

In [17]:
cleaned_filename = 'cleaned_non_majors_fall_2024.csv'
df.to_csv(cleaned_filename, index=False)
print(f"Dataset successfully saved as '{cleaned_filename}'!")

Dataset successfully saved as 'cleaned_non_majors_fall_2024.csv'!